import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import * as cheerio from "cheerio";
import JSZip from "jszip";
import { PDFParse } from "pdf-parse";

const SITE = "https://www.gazette.gov.mv";
const GAZETTE = `${SITE}/gazette`;
const IULAAN = `${SITE}/iulaan`;
const MAX_BYTES = 8 * 1024 * 1024;
const UA = "maldives-gazette-mcp/0.3";

const IULAAN_TYPES: Record<string, string> = {
  "": "All", masakkaiy: "Work / Projects", "gannan-beynunvaa": "Supplies wanted", "kuyyah-dhinun": "Property for rent", "kuyyah-hifun": "Property wanted", vazeefaa: "Job opportunity", thamreenu: "Training", neelan: "Auction", "aanmu-mauloomaathu": "General information", dhennevun: "Notice", mubaaraaiy: "Competition", "noos-bayaan": "Press release", insurance: "Insurance", beelan: "Tender / Bid",
};
const GAZETTE_TYPES: Record<string, string> = { "": "All", gaanoonu: "Law", gavaaidhu: "Regulation", garaaru: "Decision", usoolu: "Procedure", other: "Other", "tax-ruling": "Tax ruling" };
const JOB_CATEGORIES: Record<string, string> = {
  "": "All", administration: "Administration", "public-relations": "Public relations, marketing, advertising", construction: "Construction", education: "Education", finance: "Finance and accounting", "health-care": "Healthcare", "human-resource": "Human resources", "information-technology": "Information technology", insurance: "Insurance", "publishing-and-journalism": "Publishing and journalism", transport: "Transport", legal: "Legal", technical: "Technical", "customer-service": "Customer service", maintenance: "Maintenance", "support-staff": "Support staff", mechanical: "Mechanical", management: "Management",
};
const TRANSLATIONS: Record<string, string> = {
  admin: "އެޑްމިނިސްޓްރޭޓިވް", administrative: "އެޑްމިނިސްޓްރޭޓިވް", administration: "އެޑްމިނިސްޓްރޭޝަން", construction: "ކޮންސްޓްރަކްޝަން", "human resources officer": "ހިއުމަން ރިސޯސަސް އޮފިސަރ", "hr officer": "ހިއުމަން ރިސޯސަސް އޮފިސަރ", "human resources": "ހިއުމަން ރިސޯސަސް", officer: "އޮފިސަރ", manager: "މެނޭޖަރ", tender: "ބީލަން", project: "ޕްރޮޖެކްޓް", projects: "ޕްރޮޖެކްޓްތައް", job: "ވަޒީފާ", jobs: "ވަޒީފާ", software: "ސޮފްޓްވެއަރ", developer: "ޑިވެލޮޕަރ", engineer: "އިންޖިނިއަރ", technology: "ޓެކްނޮލޮޖީ", technical: "ޓެކްނިކަލް", finance: "ފައިނޭންސް", maintenance: "މެއިންޓެނަންސް", data: "ޑޭޓާ", analyst: "އެނަލިސްޓް",
};
const text = (v: cheerio.Cheerio<any> | undefined) => v?.text().replace(/\s+/g, " ").trim() ?? "";
const absolute = (href: string) => new URL(href, SITE).toString();
const queryVariants = (query: string) => { const n = query.toLowerCase().trim().replace(/\s+/g, " "); if (!n || /[^\x00-\x7F]/.test(n)) return query ? [query] : [""]; const out = [query]; if (TRANSLATIONS[n]) out.push(TRANSLATIONS[n]); const translated = n.split(" ").map(x => TRANSLATIONS[x] ?? x).join(" "); if (translated !== n) out.push(translated); n.split(" ").forEach(x => TRANSLATIONS[x] && out.push(TRANSLATIONS[x])); return [...new Set(out)]; };
async function fetchBytes(url: string, maxBytes = MAX_BYTES) { const response = await fetch(url, { headers: { "User-Agent": UA } }); const buffer = Buffer.from(await response.arrayBuffer()); if (buffer.byteLength > maxBytes) throw new Error(`response exceeds ${maxBytes} bytes`); return { response, buffer }; }
function safeSite(url: string) { const u = new URL(url); if (u.protocol !== "https:" || !["www.gazette.gov.mv", "gazette.gov.mv"].includes(u.hostname) || !(u.pathname.startsWith("/gazette") || u.pathname.startsWith("/iulaan"))) throw new Error("URL is outside the public Gazette allowlist"); return u.toString(); }
function safeAttachment(url: string) { const u = new URL(url); const storage = u.hostname === "storage.googleapis.com" && (u.pathname.startsWith("/gazette.gov.mv/docs/iulaan/") || u.pathname.startsWith("/gazette.gov.mv/docs/gazette/")); const csc = ["www.csc.gov.mv", "csc.gov.mv"].includes(u.hostname) && u.pathname.startsWith("/download/"); if (u.protocol !== "https:" || (!storage && !csc)) throw new Error("attachment is outside the official Gazette/CSC allowlist"); return u.toString(); }
function buildUrl(base: string, params: Record<string, unknown>) { const u = new URL(base); for (const [k, v] of Object.entries(params)) if (v !== undefined && v !== "" && v !== false && v !== null) u.searchParams.set(k, String(v)); return u.toString(); }
function parseOptions(html: string, source: string) { const $ = cheerio.load(html); const fields: any[] = []; $("select, input[type=text], input[type=checkbox]").each((_, el) => { const e = $(el); const name = e.attr("name") || e.attr("id"); if (!name) return; const options = e.is("select") ? e.find("option").map((_, o) => ({ value: $(o).attr("value") ?? "", label: text($(o)) })).get() : undefined; fields.push({ name, type: e.is("select") ? "select" : e.attr("type") || "text", options }); }); return { source, fields }; }
function parseIulaan(html: string, source: string) { const $ = cheerio.load(html); const results: any[] = []; $(".items.bordered").each((_, el) => { const n = $(el); const a = n.find("a.iulaan-title, a[href*='/iulaan/']").first(); if (!a.length) return; const url = absolute(a.attr("href")!); const info = n.find(".info").map((_, x) => text($(x))).get(); results.push({ title: text(n.find(".iulaan-title").first()) || text(a), url, type: text(n.find(".iulaan-type").first()) || null, office: text(n.find(".iulaan-office").first()) || null, published_date: info.find(x => x.includes("ތާރީޚު"))?.replace(/^.*?ތާރީޚު:\s*/, "") || null, deadline: info.find(x => x.includes("ސުންގަޑި"))?.replace(/^.*?ސުންގަޑި:\s*/, "") || null, source: url }); }); return { source, total: results.length, results: [...new Map(results.map(x => [x.url, x])).values()] }; }
function parseGazette(html: string, source: string) { const $ = cheerio.load(html); const results: any[] = []; $(".items-list").each((_, el) => { const n = $(el); const a = n.find("a[href*='/gazette/']").first(); if (!a.length) return; const url = absolute(a.attr("href")!); const pdf = n.find("a[href$='.pdf']").first().attr("href"); results.push({ title: text(n.find(".gazette-title, h3, h2, h4").first()) || text(a), url, category: text(n.find(".category").first()) || null, published_date: text(n.find(".published-date, .date").first()) || null, pdf_url: pdf ? absolute(pdf) : null, source: url }); }); if (!results.length) $("a[href^='/gazette/']").each((_, el) => { const url = absolute($(el).attr("href")!); if (!results.some(x => x.url === url)) results.push({ title: text($(el)), url, source: url }); }); return { source, results: [...new Map(results.map(x => [x.url, x])).values()] }; }
function attachments($: cheerio.CheerioAPI) { const out: any[] = []; $("a[href]").each((_, el) => { const h = $(el).attr("href") ?? ""; if (/\.(pdf|docx?|xlsx?)($|\?)/i.test(h)) out.push({ label: text($(el)), url: absolute(h), kind: h.toLowerCase().includes("pdf") ? "pdf" : h.toLowerCase().includes("doc") ? "docx" : "xlsx" }); }); return [...new Map(out.map(x => [x.url, x])).values()]; }
async function extractDocument(url: string, maxChars = 120000) { const u = safeAttachment(url); const { response, buffer } = await fetchBytes(u); const path = new URL(u).pathname.toLowerCase(); let extracted = ""; if (path.endsWith(".pdf")) extracted = (await new PDFParse({ data: buffer }).getText()).text; else if (path.endsWith(".docx")) { const zip = await JSZip.loadAsync(buffer); const f = zip.file("word/document.xml"); if (!f) throw new Error("DOCX has no word/document.xml"); const xml = await f.async("text"); extracted = xml.replace(/<w:p[^>]*>/g, "\n").replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim(); } else throw new Error("supported attachment types: PDF and DOCX"); const max = Math.min(250000, Math.max(1000, maxChars)); return { url: u, status: response.status, characters: extracted.length, truncated: extracted.length > max, text: extracted.slice(0, max), source: u, fetched_at: new Date().toISOString() }; }
function printUrl(idOrUrl: string) { const id = idOrUrl.match(/(\d+)(?:\D*)$/)?.[1] ?? idOrUrl; return `${IULAAN}/print/${id}`; }
const tool = (name: string, description: string, properties: any = {}, required: string[] = []) => ({ name, description, inputSchema: { type: "object", properties, ...(required.length ? { required } : {}) } });
const server = new Server({ name: "maldives-gazette", version: "0.3.0" }, { capabilities: { tools: {} } });
server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: [
  tool("gazette_status", "Check official Gazette reachability."), tool("gazette_categories", "List Gazette record categories."), tool("gazette_filter_schema", "Read the live Gazette search form and decoded filter options."), tool("search_gazette", "Search Gazette records with query, category, volume, issue, dates, and page.", { query: { type: "string" }, category: { type: "string" }, volume: { type: "string" }, issue: { type: "string" }, start_date: { type: "string" }, end_date: { type: "string" }, page: { type: "number" }, max_results: { type: "number" } }), tool("search_gazette_advanced", "Alias for the full Gazette filter search.", { query: { type: "string" }, category: { type: "string" }, volume: { type: "string" }, issue: { type: "string" }, start_date: { type: "string" }, end_date: { type: "string" }, page: { type: "number" }, max_results: { type: "number" } }), tool("get_gazette", "Read one Gazette record and its official PDF/links.", { url_or_id: { type: "string" } }, ["url_or_id"]), tool("get_gazette_print", "Read the official Gazette print/detail page.", { url_or_id: { type: "string" } }, ["url_or_id"]), tool("read_gazette_pdf", "Extract text from an official Gazette PDF.", { url: { type: "string" }, max_chars: { type: "number" } }, ["url"]), tool("search_gazette_pdf", "Search text inside an official Gazette PDF.", { url: { type: "string" }, query: { type: "string" }, max_chars: { type: "number" } }, ["url", "query"]), tool("browse_gazette", "Browse a public Gazette path.", { path: { type: "string" }, max_results: { type: "number" } }),
  tool("iulaan_categories", "List Iulaan announcement categories and job categories."), tool("iulaan_filter_schema", "Read the live Iulaan search form and decoded filter options."), tool("translate_iulaan_query", "Generate standard Dhivehi Thaana query variants.", { query: { type: "string" } }, ["query"]), tool("list_iulaan_offices", "Discover public Iulaan office/issuer links.", { page: { type: "number" }, max_results: { type: "number" } }), tool("search_iulaan", "Search Iulaan announcements with all website filters.", { query: { type: "string" }, announcement_type: { type: "string" }, office: { type: "string" }, job_category: { type: "string" }, start_date: { type: "string" }, end_date: { type: "string" }, open_only: { type: "boolean" }, page: { type: "number" }, max_results: { type: "number" } }), tool("search_iulaan_advanced", "Alias for the full Iulaan filter search.", { query: { type: "string" }, announcement_type: { type: "string" }, office: { type: "string" }, job_category: { type: "string" }, start_date: { type: "string" }, end_date: { type: "string" }, open_only: { type: "boolean" }, page: { type: "number" }, max_results: { type: "number" } }), tool("browse_iulaan_pages", "Browse a filtered Iulaan page with pagination.", { page: { type: "number" }, query: { type: "string" }, announcement_type: { type: "string" }, job_category: { type: "string" }, office: { type: "string" }, open_only: { type: "boolean" }, max_results: { type: "number" } }), tool("get_iulaan", "Read one Iulaan posting, visible text, print URL, and attachments.", { url_or_id: { type: "string" } }, ["url_or_id"]), tool("get_iulaan_print", "Read the official Iulaan print view.", { url_or_id: { type: "string" } }, ["url_or_id"]), tool("list_iulaan_attachments", "List official Iulaan TOR/application attachments.", { url_or_id: { type: "string" } }, ["url_or_id"]), tool("read_iulaan_attachment", "Extract text from an official Iulaan or Gazette PDF/DOCX attachment.", { url: { type: "string" }, max_chars: { type: "number" } }, ["url"]), tool("search_iulaan_attachment_text", "Search within an official Iulaan attachment.", { url: { type: "string" }, query: { type: "string" }, max_chars: { type: "number" } }, ["url", "query"]),
] }));
async function pageData(url: string, kind: "gazette" | "iulaan") { const { response, buffer } = await fetchBytes(url); const html = buffer.toString("utf8"); return { response, buffer, html, parsed: kind === "gazette" ? parseGazette(html, url) : parseIulaan(html, url) }; }
async function searchIulaan(a: Record<string, any>) { const variants = queryVariants(a.query ?? ""); const merged = new Map<string, any>(); let first = ""; for (const q of variants) { const u = buildUrl(IULAAN, { type: a.announcement_type, office: a.office, "job-category": a.job_category, q, "start-date": a.start_date, "end-date": a.end_date, "open-only": a.open_only, page: a.page }); if (!first) first = u; const p = await pageData(u, "iulaan"); if (!p.response.ok) throw new Error(`HTTP ${p.response.status}`); p.parsed.results.forEach((r: any) => { r.matched_query = q; merged.set(r.url, r); }); } return { url: first, total: merged.size, results: [...merged.values()].slice(0, Math.min(50, a.max_results ?? 20)), status: 200, query: a.query ?? "", query_variants: variants, filters: { announcement_type: a.announcement_type ?? "", job_category: a.job_category ?? "", office: a.office ?? "", start_date: a.start_date ?? "", end_date: a.end_date ?? "", open_only: !!a.open_only, page: a.page ?? 1 }, fetched_at: new Date().toISOString() }; }
server.setRequestHandler(CallToolRequestSchema, async req => { const name = req.params.name; const a = (req.params.arguments ?? {}) as Record<string, any>; try {
  if (name === "gazette_status") { const { response } = await fetchBytes(GAZETTE); return { content: [{ type: "text", text: JSON.stringify({ ok: response.ok, status: response.status, source: GAZETTE, checked_at: new Date().toISOString() }) }] }; }
  if (name === "gazette_categories") return { content: [{ type: "text", text: JSON.stringify({ source: GAZETTE, categories: Object.entries(GAZETTE_TYPES).map(([value, label]) => ({ value, label, url: buildUrl(GAZETTE, { type: value }) })) }, null, 2) }] };
  if (name === "gazette_filter_schema") { const p = await pageData(GAZETTE, "gazette"); return { content: [{ type: "text", text: JSON.stringify({ ...parseOptions(p.html, GAZETTE), category_values: GAZETTE_TYPES, status: p.response.status }, null, 2) }] }; }
  if (name === "search_gazette" || name === "search_gazette_advanced") { const u = buildUrl(GAZETTE, { type: a.category, volume: a.volume, issue: a.issue, q: a.query, "start-date": a.start_date, "end-date": a.end_date, page: a.page }); const p = await pageData(u, "gazette"); return { content: [{ type: "text", text: JSON.stringify({ ...p.parsed, status: p.response.status, filters: a, results: p.parsed.results.slice(0, Math.min(50, a.max_results ?? 20)), fetched_at: new Date().toISOString() }, null, 2) }] }; }
  if (name === "browse_gazette") { const u = safeSite(absolute(a.path ?? "/gazette")); const p = await pageData(u, "gazette"); return { content: [{ type: "text", text: JSON.stringify({ ...p.parsed, status: p.response.status, results: p.parsed.results.slice(0, Math.min(50, a.max_results ?? 20)), fetched_at: new Date().toISOString() }, null, 2) }] }; }
  if (name === "iulaan_categories") return { content: [{ type: "text", text: JSON.stringify({ source: IULAAN, announcement_types: Object.entries(IULAAN_TYPES).map(([value, label]) => ({ value, label, url: buildUrl(IULAAN, { type: value }) })), job_categories: Object.entries(JOB_CATEGORIES).map(([value, label]) => ({ value, label })) }, null, 2) }] };
  if (name === "iulaan_filter_schema") { const p = await pageData(IULAAN, "iulaan"); return { content: [{ type: "text", text: JSON.stringify({ ...parseOptions(p.html, IULAAN), announcement_types: IULAAN_TYPES, job_categories: JOB_CATEGORIES, status: p.response.status }, null, 2) }] }; }
  if (name === "translate_iulaan_query") { const v = queryVariants(a.query); return { content: [{ type: "text", text: JSON.stringify({ original_query: a.query, query_variants: v, translated_variants: v.slice(1) }, null, 2) }] }; }
  if (name === "list_iulaan_offices") { const u = buildUrl(IULAAN, { page: a.page }); const p = await pageData(u, "iulaan"); const $ = cheerio.load(p.html); const offices: any[] = []; $("a[href*='/iulaan?office=']").each((_, el) => { offices.push({ label: text($(el)), url: absolute($(el).attr("href")!) }); }); const unique = [...new Map(offices.map(x => [x.url, x])).values()]; return { content: [{ type: "text", text: JSON.stringify({ source: u, status: p.response.status, total: unique.length, offices: unique.slice(0, Math.min(500, a.max_results ?? 500)) }, null, 2) }] }; }
  if (name === "search_iulaan" || name === "search_iulaan_advanced" || name === "browse_iulaan_pages") { const result = await searchIulaan({ ...a, query: name === "browse_iulaan_pages" ? (a.query ?? "") : a.query }); return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] }; }
  if (name === "get_gazette" || name === "get_iulaan") { const base = name === "get_gazette" ? GAZETTE : IULAAN; const u = safeSite(a.url_or_id?.startsWith("http") ? a.url_or_id : `${base}/${a.url_or_id}`); const { response, html } = await pageData(u, name === "get_gazette" ? "gazette" : "iulaan"); const $ = cheerio.load(html); const at = attachments($); const visible = $("body").text().replace(/\s+/g, " ").trim(); const id = u.match(/(\d+)(?:\D*)$/)?.[1] ?? null; return { content: [{ type: "text", text: JSON.stringify({ url: u, status: response.status, title: text($(".iulaan-title, .gazette-title, h1, h2").first()), employer: text($(".office-name, .iulaan-office").first()) || null, print_url: name === "get_iulaan" && id ? `${IULAAN}/print/${id}` : null, pdf_url: at.find(x => x.kind === "pdf")?.url ?? null, attachments: at, visible_text: visible.slice(0, 250000), source: u, fetched_at: new Date().toISOString() }, null, 2) }] }; }
  if (name === "get_iulaan_print" || name === "get_gazette_print") { const u = name === "get_iulaan_print" ? safeSite(printUrl(a.url_or_id)) : safeSite(a.url_or_id.startsWith("http") ? a.url_or_id : `${GAZETTE}/${a.url_or_id}`); const { response, html } = await pageData(u, name === "get_iulaan_print" ? "iulaan" : "gazette"); const $ = cheerio.load(html); return { content: [{ type: "text", text: JSON.stringify({ url: u, status: response.status, title: text($("h1,h2,.iulaan-title,.gazette-title").first()), text: $("body").text().replace(/\s+/g, " ").trim().slice(0, 250000), source: u, fetched_at: new Date().toISOString() }, null, 2) }] }; }
  if (name === "list_iulaan_attachments") { const u = safeSite(a.url_or_id?.startsWith("http") ? a.url_or_id : `${IULAAN}/${a.url_or_id}`); const { response, html } = await pageData(u, "iulaan"); const $ = cheerio.load(html); return { content: [{ type: "text", text: JSON.stringify({ url: u, status: response.status, attachments: attachments($), source: u }, null, 2) }] }; }
  if (name === "read_iulaan_attachment" || name === "read_gazette_pdf") { const result = await extractDocument(a.url, a.max_chars); return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] }; }
  if (name === "search_iulaan_attachment_text" || name === "search_gazette_pdf") { const result = await extractDocument(a.url, a.max_chars ?? 250000); const q = String(a.query).toLowerCase(); const lines = result.text.split(/\n+/); const matches = lines.filter(x => x.toLowerCase().includes(q)); const { text: _documentText, ...metadata } = result; return { content: [{ type: "text", text: JSON.stringify({ ...metadata, query: a.query, matches: matches.slice(0, 100), match_count: matches.length }, null, 2) }] }; }
  throw new Error(`unknown tool: ${name}`);
 } catch (error) { return { isError: true, content: [{ type: "text", text: JSON.stringify({ error: error instanceof Error ? error.name : "Error", message: String(error), tool: name }) }] }; } });
await server.connect(new StdioServerTransport());
